/* ============================================================
   Golden Limits — DATA (single source of truth)
   Loaded by index.html. Update this file ONLY.
   End-of-day routine: append each EXECUTED trade below, bump last_updated.
   Fields: id, date "YYYY-MM-DD", dir "LONG|SHORT", entry, pips (achieved, 1pip=$0.1),
           outcome "TP3|TP1|SL", grade 0-10, kind "limit|market", note (English, human tone).
   kind = "limit"  -> published limit-zone card that filled passively (counts as a
                       success if it filled and reached >=TP1, even without a live entry).
   kind = "market" -> my live sniper entry on a real-time reaction.
   Cancelled/expired signals -> update activity counters (no P&L).
============================================================ */
window.GL_DATA = {
  last_updated: "2026-07-13",
  activity: { cancelled: 29, pending: 0 },
  trades: [
    { id:4,  date:"2026-06-01", dir:"SHORT", entry:4479,   pips:70,   outcome:"TP1", grade:7, kind:"market", note:"First profit. TP1 hit, BE not moved (management lesson)." },
    { id:5,  date:"2026-06-02", dir:"LONG",  entry:4525.6, pips:94,   outcome:"TP1", grade:7, kind:"market", note:"Sweep-reclaim L1, runner back to BE." },
    { id:6,  date:"2026-06-02", dir:"LONG",  entry:4526,   pips:80,   outcome:"TP1", grade:7, kind:"market", note:"Sweep-reclaim L1 on NY volume, runner BE." },
    { id:7,  date:"2026-06-02", dir:"SHORT", entry:4521,   pips:230,  outcome:"TP3", grade:7, kind:"market", note:"Break+retest range low. First full TP3 winner." },
    { id:8,  date:"2026-06-02", dir:"SHORT", entry:4494,   pips:-50,  outcome:"SL",  grade:6, kind:"market", note:"Shorted into own demand vs H1. Manual exit on reclaim." },
    { id:9,  date:"2026-06-02", dir:"LONG",  entry:4483,   pips:70,   outcome:"TP1", grade:7, kind:"market", note:"Sweep-reclaim L6, runner BE." },
    { id:13, date:"2026-06-03", dir:"SHORT", entry:4464,   pips:160,  outcome:"TP3", grade:7, kind:"market", note:"Chop-fade top edge + 5m OB. Full TP3 winner." },
    { id:16, date:"2026-06-04", dir:"SHORT", entry:4512,   pips:350,  outcome:"TP3", grade:8, kind:"market", note:"Reject premium supply S2 4514-28. Best trade." },
    { id:19, date:"2026-06-05", dir:"SHORT", entry:4465,   pips:70,   outcome:"TP1", grade:8, kind:"market", note:"Reject Asia High supply, runner BE through NFP." },
    { id:20, date:"2026-06-05", dir:"LONG",  entry:4374,   pips:-130, outcome:"SL",  grade:7, kind:"market", note:"Counter-trend bounce on NFP trend day. Did not work." },
    { id:21, date:"2026-06-08", dir:"SHORT", entry:4340,   pips:200,  outcome:"TP1", grade:8, kind:"limit",  note:"Published limit zone at Asia High + H1 supply. Filled passively, TP1 hit, banked in profit. Thin volume day." },
    { id:23, date:"2026-06-09", dir:"SHORT", entry:4332,   pips:80,   outcome:"TP1", grade:7, kind:"market", note:"Break+retest of 4338-42 zone on volume. Scalp, TP1 banked, runner BE." },
    { id:26, date:"2026-06-09", dir:"SHORT", entry:4284,   pips:340,  outcome:"TP3", grade:7, kind:"market", note:"Trend-continuation sell-the-bounce reject at broken structure in ~1000p down-day. Full TP3 winner." },
    { id:27, date:"2026-06-09", dir:"SHORT", entry:4264,   pips:80,   outcome:"TP1", grade:7, kind:"market", note:"Trend-continuation sell-the-bounce reject at 4267-4278 sell-zone. TP1 banked, runner back to BE." },
    { id:30, date:"2026-06-10", dir:"SHORT", entry:4168,   pips:-60,  outcome:"SL",  grade:7, kind:"market", note:"Trend retest-short 4172.5. Stop sat 1.5p above retest high, swept by wick before TP1. CPI-day whipsaw." },
    { id:31, date:"2026-06-10", dir:"SHORT", entry:4161,   pips:-50,  outcome:"SL",  grade:8, kind:"market", note:"Break+retest of 4163-4179 consolidation. Range reclaimed, false break swept stop. News-whipsaw before CPI." },
    { id:32, date:"2026-06-11", dir:"LONG",  entry:4085.5, pips:205,  outcome:"TP2", grade:7, kind:"market", note:"Zone-reaction long off 15m bull OB after overnight V-reversal. TP1+TP2 banked, runner closed on published trail 4101. TP3 missed by 80p." },
    { id:34, date:"2026-06-11", dir:"LONG",  entry:4086,   pips:-65,  outcome:"SL",  grade:6.5, kind:"market", note:"Second test of the morning demand zone. Procedurally clean entry, but the zone was spent — third push broke it. Last sub-7 trade: channel bar raised to 7+." },
    { id:35, date:"2026-06-11", dir:"LONG",  entry:4089.5, pips:-70,  outcome:"SL",  grade:7, kind:"market", note:"Sweep-reclaim long off equal lows. Ran +66p and missed TP1 by 1.5p, then sell-side pressure broke the floor ahead of ECB. Market cancelled the setup." },
    { id:36, date:"2026-06-11", dir:"LONG",  entry:4060,   pips:180,  outcome:"TP1", grade:7, kind:"limit",  note:"Published limit at the day's key demand 4052-4060, filled on the PPI spike. First retest of the major origin: TP1 banked, runner peaked +330p near TP2 then closed at breakeven." },
    { id:37, date:"2026-06-11", dir:"LONG",  entry:4095,   pips:-45,  outcome:"SL",  grade:7.5, kind:"market", note:"Evening break+retest above 4093. The breakout turned out to be a stop sweep and price fell back into the range. Tight stop kept the damage small." },
    { id:41, date:"2026-06-12", dir:"LONG",  entry:4177,   pips:80,   outcome:"TP1", grade:8.5, kind:"market", note:"London swept the equal lows 4171 into the 15m OB and reclaimed — entry on the first reject close. TP1 banked, runner back to BE." },
    { id:42, date:"2026-06-12", dir:"LONG",  entry:4217,   pips:90,   outcome:"TP1", grade:8, kind:"market", note:"Trend retest after the 4205 structure break: pullback into the flip zone, reclaim confirmed. TP1 banked, runner held through hours of chop at the highs then closed at BE." },
    { id:43, date:"2026-06-12", dir:"LONG",  entry:4208,   pips:60,   outcome:"TP1", grade:7.5, kind:"market", note:"Sweep reclaim off the 4194-4200 floor: stops swept under the round number, buyers absorbed and reclaimed in one impulse bar. TP1 banked in 10 minutes, runner back to BE on the pullback." },
    { id:44, date:"2026-06-12", dir:"LONG",  entry:4201.5, pips:-50,  outcome:"SL",  grade:7.5, kind:"market", note:"Second sweep-reclaim attempt at a tired floor after eight defenses with fading bounces. The reclaim candle faded after entry and sellers pushed through. Lesson logged: enter on fully closed bars only, skip exhausted zones." },
    { id:45, date:"2026-06-15", dir:"LONG",  entry:4344,   pips:-100, outcome:"SL",  grade:7, kind:"market", note:"Breakout long above 4344. Entered at the top of the move into multi-TF supply instead of on a pullback — it failed and rolled over. Wrong-place entry." },
    { id:46, date:"2026-06-15", dir:"LONG",  entry:4364,   pips:-140, outcome:"SL",  grade:7, kind:"market", note:"Reclaim of the week high at the very top of the coil. Again chased the end of the move, not a retest into support. Day's biggest loss." },
    { id:47, date:"2026-06-15", dir:"LONG",  entry:4324,   pips:-60,  outcome:"SL",  grade:7.5, kind:"limit", note:"Published limit at the 4324 swing-low — a proper retest into support, not a top. Held over 3h in a dead overnight coil 4318-4328 that gave two fake reclaims and no momentum, then lost the floor into SL. Right idea, wrong timing after two earlier stops." },
    { id:48, date:"2026-06-17", dir:"LONG",  entry:4319,   pips:140,  outcome:"TP2", grade:7.5, kind:"market", note:"Asia-low liquidity sweep + reclaim — a clean retest into support, not a chase. Price swept the session low 4317.7, reclaimed, and the entry fired on the close. TP1 and TP2 banked, stop locked in profit, runner still riding toward TP3. Patient FOMC-day scalp." },
    { id:49, date:"2026-06-17", dir:"SHORT", entry:4341,   pips:-15,  outcome:"SL",  grade:7,   kind:"market", note:"Counter-trend fade of fresh 15m supply at the range top with a closed 3m rejection. The stop sat inside the zone and a wick to the very top swept it before any follow-through. Small loss — stop too tight, the zone actually held on the close." },
    { id:50, date:"2026-06-17", dir:"SHORT", entry:4355,   pips:-70,  outcome:"SL",  grade:6,   kind:"limit",  note:"Published premium-supply limit at the range top. Filled as price pushed up, then the same impulse broke clean through into the weekly high and stopped it out. The zone was not fresh and the breakout ran it over." },
    { id:51, date:"2026-06-18", dir:"LONG",  entry:4276,   pips:-110, outcome:"SL",  grade:7,   kind:"limit",  note:"Published discount-demand limit at the Asia low + 15m bull OB after the sell-side sweep. Filled on the London cascade, but the broken 4296 floor turned into a vertical flush straight through the zone and the stop. Set-and-forget stop protected capital as designed." },
    { id:52, date:"2026-06-18", dir:"SHORT", entry:4249,   pips:90,   outcome:"TP1", grade:7,   kind:"market", note:"By-trend continuation in the post-FOMC downtrend. Sold the retest of the broken 4250 shelf on a closed 3m rejection — a clean reaction, not a chase. TP1 banked, runner spiked back to breakeven. Winner." },
    { id:53, date:"2026-06-18", dir:"SHORT", entry:4270,   pips:320,  outcome:"TP3", grade:7,   kind:"market", note:"Post-news bounce swept the range-high liquidity into the 15m bear FVG 4273-82 and printed a closed 3m rejection — a clean bull-trap short. All three targets hit as price rolled back toward the FOMC crash low. Trade of the day, full TP3 winner." },
    { id:54, date:"2026-06-18", dir:"LONG",  entry:4221,   pips:90,   outcome:"TP1", grade:7.5, kind:"market", note:"Counter-trend long off the FOMC crash low 4219 — swept the major sell-side liquidity and reclaimed on a closed 3m bar. Nearly stopped on a deep retest, held by a whisker above the tight structural stop, then bounced to TP1. Runner could not break TP2 in the downtrend and trailed out at breakeven. TP1 banked. Weakest setup of the day — thin counter-trend R, saved by the structural stop and closed-bar discipline." },
    { id:55, date:"2026-06-19", dir:"SHORT", entry:4177,   pips:300,  outcome:"TP3", grade:7,   kind:"market", note:"By-trend turtle-soup at the 4166-76 OB on thin Juneteenth liquidity — swept the buy-side above 4176 and closed back below, entry on the sealed reject. All three targets hit on a clean set-and-forget run toward the daily draw. Waited out two hours of holiday chop and correctly declined a marginal earlier reject. Full TP3 winner." },
    { id:56, date:"2026-06-22", dir:"LONG",  entry:4180,   pips:40,   outcome:"TP1", grade:7,   kind:"market", note:"Counter-trend §2B long off the deep H1 FVG demand 4170.7 — swept the session low and reclaimed on a closed 3m bar. TP1 banked, runner trailed back to breakeven. Logged at the honest achievable fill ~4180 (+40), not the card's optimistic price — kept it reproducible. Thin Monday, clean read, weak counter-trend R." },
    { id:57, date:"2026-06-23", dir:"SHORT", entry:4132,   pips:-100, outcome:"SL",  grade:7,   kind:"market", note:"By-trend reject of the 4137-45 supply in the downtrend — right thesis. But the reject bar was a violent one-bar displacement that overshot the zone, so the market fill landed in no-man's-land below it, with no level underneath. The stop was crammed inside the zone for R and a wick swept it before the move; a stop at the zone's far edge would have survived. Mid-air entry, stop anchored to the fill instead of structure." },
    { id:58, date:"2026-06-23", dir:"SHORT", entry:4123,   pips:-80,  outcome:"SL",  grade:7,   kind:"market", note:"Continuation short on the breakdown of an internal range level 4127 — but the range (true floor 4091) was still intact, so it was a false break. Price reclaimed immediately and ground back up into the stop with no follow-through. The structural stop was placed correctly this time; the trade itself was wrong — an internal breakout traded inside a range, taken 30 minutes after the first stop. Overtrade in chop." },
    { id:59, date:"2026-06-25", dir:"SHORT", entry:3997,   pips:190,  outcome:"TP2", grade:7,   kind:"market", note:"By-trend reject of the range-top supply 3998-4018 after a London-long accumulation coil — swept the upper edge and closed a 3m bar back below. The shallow-reject entry I flagged as risky on the way in, with DXY leaning against it, paid off on pure holding discipline: TP1 then TP2 banked over ~3 hours, runner trailed out near 3988. Almost closed it manually at breakeven mid-trade and was right not to. Winner." },
    { id:60, date:"2026-06-25", dir:"SHORT", entry:4040,   pips:110,  outcome:"TP1", grade:7,   kind:"market", note:"By-trend reject of the H4 bear-FVG supply 4034-4042 after the post-PCE squeeze broke the day range up. Closed 3m rejection below 4034 was the trigger; a 4-minute decision delay slid the actual fill up to the zone top 4040, which gave a tight 50p structural stop. TP1 +110 banked, then the runner sat through ~2.5h of dead chop under the supply and trailed out at breakeven — TP2 never reached. The trade we nearly cut for a loss in the chop came back and paid. Lesson logged: fire the planned-zone card instantly on the closed reject, don't re-derive what the plan already settled." },
    { id:61, date:"2026-06-29", dir:"LONG",  entry:4013,   pips:90,   outcome:"TP1", grade:7,   kind:"market", note:"Counter-trend §2B long off the H4 demand 4006-4012 after an impulsive markdown swept every intraday low. Price drove under the H4 low to 4000.3 and reclaimed on a closed 3m bar — entry on the sealed reclaim ~4013. TP1 +90 banked in six minutes, then the runner coiled ~1.5h under the 4035 target and trailed out at breakeven; TP2 never reached. Wide sweep-stop made for thin TP1 R, but the planned deep-demand bounce was banked and protected with BE. Correctly skipped a second test of the same zone later — not fresh. Winner." },
    { id:62, date:"2026-06-30", dir:"SHORT", entry:4020,   pips:-80,  outcome:"SL",  grade:7,   kind:"market", note:"Failed-breakdown short on the Asian-High reclaim 4022.5 after 3.5h of range chop. The 3m closed 35p below the level — a clean impulsive break on paper — but it was the middle of a multi-hour 4020-4034 whipsaw range, not an edge. Price never followed through, ground back up and swept the stop. TP1 4011 was missed by ~$0.2 three separate times. Lesson logged: in a multi-hour whipsaw range, fade the edges (4011 / 4047), never a mid-range break." },
    { id:63, date:"2026-07-01", dir:"SHORT", entry:3982,   pips:100,  outcome:"TP1", grade:7,   kind:"market", note:"By-trend sweep-and-reject at the top of the box: price swept the 15m swing high 3982.98 and closed a 3m bar 31p back below it — a clean impulse reject with full room down. TP1 banked in ~20 minutes, then the swing held the lid three times and the runner coiled under it with no downside push, trailing out at breakeven. Textbook top-of-range reject. Note: BE sat exactly on the swing edge, so the retest of that edge clipped it before continuation — the recurring break-even-retest pattern." },
    { id:64, date:"2026-07-01", dir:"SHORT", entry:3986,   pips:-50,  outcome:"SL",  grade:7,   kind:"market", note:"Tier-2 fade of the H1 bear-FVG supply 3986-93 on the bounce off 3960. Two closed 3m rejections under the edge triggered it, but the intraday leg into the zone was a strong +$3 up-impulse, so the FVG acted as a speed-bump not a wall. Pushed +43p (TP1 missed by ~5p), then reclaimed and ground up into the stop. Lesson logged: don't fade an HTF FVG against a fresh intraday impulse — or set TP1 closer." },
    { id:65, date:"2026-07-01", dir:"LONG",  entry:4016,   pips:340,  outcome:"TP3", grade:7,   kind:"market", note:"By-trend reclaim of the 15m bull FVG 3998-4015 demand. Price broke the 4023 compression down, tapped the imbalance (low 4012.86), and closed a 3m bar back at 4020.32 — a >25p impulse reclaim above the FVG top. Entered on the sealed bar with the structural stop under the reclaim low. Ran the full ladder TP1-TP2-TP3 set-and-forget. Cleared the cooldown after the prior stop — took it autonomously as the qualifying by-trend A-setup. Trade of the day, full TP3 winner." },
    { id:66, date:"2026-07-02", dir:"LONG",  entry:4062,   pips:-80,  outcome:"SL",  grade:7,   kind:"market", note:"Pre-NFP by-trend tap of the 4055-62 demand stack. A sluggish 16p reclaim plus a bare 'held the edge' bar was taken as confirmation — too thin. Price sat on the zone for 80 minutes with fading bounces, then a sweep ran 23p under the swing and clipped the stop 8p before the reversal; the zone later paid TP1 without us. Post-audit regraded 6 (the 'FVG stack' was one gap on two TFs). Two lessons logged: weak reclaims need an active confirming bar, and London/pre-news stops need a 25-30p buffer under the swept structure." },
    { id:67, date:"2026-07-02", dir:"LONG",  entry:4117,   pips:80,   outcome:"TP1", grade:7,   kind:"market", note:"Post-NFP pullback long at the top of the giant NFP imbalance 4110-14. Tap 4114.06, weak reclaim, then a proper confirming bar with a new high — the tightened confirmation rule applied cleanly this time. TP1 +80 banked three minutes after the card, stop moved to breakeven, and a single spike then swept BE by half a pip before price turned back up — the recurring BE-stop-retest pattern, runner lost to it again. Banked winner; BE-buffer question queued for review." },
    { id:69, date:"2026-07-06", dir:"LONG",  entry:4147,   pips:190,  outcome:"TP2", grade:7.5, kind:"market", note:"Monday-open long at the Friday demand origin 4146.7-52 after Asia double-swept the highs at 4202 and sold off $58. The morning low swept the zone's lower edge into the flip stack, a weak reclaim was confirmed by an active bar, and price based with higher lows — entry on the sealed confirmation. The wide buffered stop 4137.5 survived a double near-miss of breakeven by 3p before the LH 4160.7 broke and the leg ran. TP1 and TP2 banked, runner trailed out at 4155 locking profit. +190 to the furthest target. Winner." },
    { id:71, date:"2026-07-07", dir:"SHORT", entry:4132,   pips:80,   outcome:"TP1", grade:7,   kind:"market", note:"By-trend impulse reject off the 4131.5-41 supply after two sluggish taps were correctly skipped — the trigger bar closed 38p through the edge. Price then ran the zone 90p against the entry and sat under 4139 for three hours before sliding to TP1. The honest wide stop behind the lower high 4146 held the whole ride. TP1 banked, runners taken out at breakeven on the second push up. Patience trade — ugly path, clean result." },
    { id:72, date:"2026-07-07", dir:"SHORT", entry:4160,   pips:-120, outcome:"SL",  grade:7,   kind:"limit",  note:"Published limit at the middle of the wide 4152-68 supply, filled on a post-news vertical that had already swept two lower highs on the way up. The same impulse went straight through the zone without a single rejection close and took the stop. The H1 closed above the zone right after — structure flipped up, the supply was already dead. Filled into momentum; no reject filter on a limit." },
    { id:73, date:"2026-07-07", dir:"LONG",  entry:4162,   pips:80,   outcome:"TP1", grade:7.5, kind:"market", note:"First touch of the fresh 15m FVG 4158.4-63 stacked with the H1 imbalance after the structure flip up. Tap, weak reclaim, then an active confirming bar with a new high — the tightened confirmation rule fired the entry. TP1 banked eleven minutes in, price pushed to 4178 missing TP2 by 16p, and the pullback took the runners out at breakeven. Textbook flip-and-go continuation." },
    { id:74, date:"2026-07-07", dir:"LONG",  entry:4136.7, pips:73,   outcome:"TP1", grade:7,   kind:"market", note:"First touch of the last bullish 15m OB 4131.8-36.3 holding the up-leg. A razor-thin reclaim was confirmed by an active bar closing above the reject — entry on the sealed close. TP1 banked in 16 minutes, then the runner ground sideways under 4148 for two hours and the evening dump took it out at breakeven — minutes before price collapsed $45 to 4092. The split ladder banked the move and the BE stop dodged the crash." },
    { id:77, date:"2026-07-10", dir:"SHORT", entry:4110,   pips:160,  outcome:"TP2", grade:7,   kind:"market", note:"Breakdown-retest short from the day plan: London broke the 4106.8 demand base, price retested 4106-10 from below and printed an impulsive 33p closed rejection off 4109.92 — entry on the sealed bar. Clean lower-low run with max drawdown of 6p: TP1 banked in 50 minutes, TP2 tagged at 4094.4. A V-reversal snapped price back above the trail level within minutes, so the runner was closed at 4098 locking the move. +160 to the furthest target. Winner." },
    { id:78, date:"2026-07-10", dir:"SHORT", entry:4104,   pips:80,   outcome:"TP1", grade:7,   kind:"market", note:"Floor-break short: the 4104-07 floor had been defended four times and finally snapped with a closed 3m break at 4100.2 on rising volume — entry on the sealed bar, no retest wait since the break itself was the trigger. TP1 banked in seven minutes. The day's second V-reversal then ripped price straight back up and the runner was taken out at the server break-even. +80 banked on a whipsaw day where the BE discipline saved a full stop." },
    { id:79, date:"2026-07-10", dir:"SHORT", entry:4096,   pips:80,   outcome:"TP1", grade:7.5, kind:"market", note:"Two-phase breakdown-retest: the day low 4094.4 broke with a record-volume 70p impulse close — correctly skipped as a chase — then price retested 4092-96, swept the level to 4097 and printed a 27p closed rejection. Entry on the sealed bar. TP1 tagged one minute later on the continuation flush. The third V-bounce of the day then reclaimed the runner at break-even. Fast, clean, per-playbook execution of the skip-then-retest pattern." },
    { id:80, date:"2026-07-13", dir:"LONG",  entry:4064,   pips:-80,  outcome:"SL",  grade:7.5, kind:"market", note:"Post-sweep retest long on liquidation Monday: gap-down day swept the EQL pool to 4044, printed a 15m CHoCH up, and price pulled back into the flipped 4064.7 floor. Weak reclaim confirmed by an active bar — clean trigger, entry at the anchor, no chase. Five minutes later a single 145p liquidation bar went straight through the invalidation and the stop with no retest. Rules held; the day did not — an early CHoCH without acceptance above 4080 was too thin a layer against a live cascade." },
    { id:81, date:"2026-07-13", dir:"LONG",  entry:4034,   pips:-70,  outcome:"SL",  grade:7,   kind:"market", note:"Full §2B counter-trend at the HTF demand cluster 4033-41: EQL swept first, sweep-wick through the zone floor to 4029.8, closed reclaim back inside, active confirming bar — every branch of the tree checked. Seven minutes later a fresh 280p liquidation impulse wiped the stop, the zone and the week low in one bar. Second knife-catch stop of the day. Lesson hard-logged: on a cascade liquidation day even a complete §2B counter-long does not work — no counter-trend on trend days, full stop." }
  ]
};
